/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#924a37',
        'primary-container': '#e38b75',
        'primary-fixed': '#ffdad2',
        'primary-fixed-dim': '#ffb4a2',
        'on-primary': '#ffffff',
        'on-primary-container': '#622516',
        'on-primary-fixed': '#3b0901',
        'on-primary-fixed-variant': '#753322',
        'inverse-primary': '#ffb4a2',
        secondary: '#4e616c',
        'secondary-container': '#d1e6f2',
        'secondary-fixed': '#d1e6f2',
        'secondary-fixed-dim': '#b5c9d6',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#546772',
        'on-secondary-fixed': '#0a1e27',
        'on-secondary-fixed-variant': '#364953',
        tertiary: '#55624d',
        'tertiary-container': '#98a68d',
        'tertiary-fixed': '#d9e7cc',
        'tertiary-fixed-dim': '#bdcbb1',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#2f3c28',
        'on-tertiary-fixed': '#131f0e',
        'on-tertiary-fixed-variant': '#3e4a36',
        surface: '#fbf9f5',
        'surface-dim': '#dbdad6',
        'surface-bright': '#fbf9f5',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3ef',
        'surface-container': '#efeeea',
        'surface-container-high': '#eae8e4',
        'surface-container-highest': '#e4e2de',
        'surface-variant': '#e4e2de',
        'surface-tint': '#924a37',
        'on-surface': '#1b1c1a',
        'on-surface-variant': '#54433f',
        'inverse-surface': '#30312e',
        'inverse-on-surface': '#f2f0ed',
        outline: '#87736e',
        'outline-variant': '#d9c1bc',
        background: '#fbf9f5',
        'on-background': '#1b1c1a',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        mustard: '#E6B34B',
        'mustard-dark': '#c49520',
      },
      borderRadius: {
        DEFAULT: '1rem',
        sm: '0.5rem',
        md: '1.5rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
        gutter: '24px',
        'container-max': '1280px',
      },
      fontFamily: {
        display: ['"Antonio"', 'sans-serif'],
        body: ['"Noto Sans"', 'sans-serif'],
        sans: ['"Noto Sans"', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em' }],
        'display-xl': ['64px', { lineHeight: '1.1', letterSpacing: '-0.03em' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '500' }],
        'headline-sm': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['13px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-xs': ['12px', { lineHeight: '1.2', letterSpacing: '0.03em', fontWeight: '500' }],
      },
      boxShadow: {
        mediterranean: '0 10px 40px -10px rgba(74, 59, 40, 0.08)',
        card: '0 4px 24px -4px rgba(74, 59, 40, 0.06)',
        soft: '0 2px 12px rgba(74, 59, 40, 0.05)',
      },
      backdropBlur: {
        glass: '12px',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-out',
        'slide-up': 'slideUp 0.5s ease-out',
        'slide-up-delay': 'slideUp 0.5s ease-out 0.1s both',
        'spin-slow': 'spin 2s linear infinite',
        pulse: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'scale-in': 'scaleIn 0.3s ease-out',
        shimmer: 'shimmer 1.5s infinite',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        slideUp: { '0%': { opacity: '0', transform: 'translateY(24px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        scaleIn: { '0%': { opacity: '0', transform: 'scale(0.95)' }, '100%': { opacity: '1', transform: 'scale(1)' } },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
      maxWidth: {
        container: '1280px',
      },
    },
  },
  plugins: [],
};
